spyads_dev/config/routes.rb
Ixsellapp::Application.routes.draw do
  
  resources :rulesets do
    resources :rules do
    end
  end

  get "ixsell/query"

  get "ixsell/home"

  match "ixsell" => "ixsell#home"
  root :to => 'ixsell#home'

  resources :ads
  resources :users

end

spyads_dev/app/models/rule.rb
class Rule < ActiveRecord::Base
  belongs_to :ad
  belongs_to :ruleset
end

spyads_dev/app/controllers/rules_controller.rb
class RulesController < ApplicationController
  # GET /rules
  # GET /rules.json
  def index
    @ruleset = Ruleset.find_by_id(params[:ruleset_id])
    @rules = @ruleset.rules

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rules }
    end
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
    @ruleset = Ruleset.find_by_id(params[:ruleset_id])
    @rule = @ruleset.rules.find_by_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rule }
    end
  end

  # GET /rulesets/1/rules/new
  # GET /rulesets/1/rules/new.json
  def new
    @ruleset = Ruleset.find(params[:ruleset_id])
    @rule = @ruleset.rules.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rule }
    end
  end

  # GET /rules/1/edit
  def edit
    @ruleset = Ruleset.find(params[:ruleset_id])
    @rule = @ruleset.rules.find(params[:id])
  end

  # POST /rules
  # POST /rules.json
  def create
    @ruleset = Ruleset.find(params[:ruleset_id])
    @rule = @ruleset.rules.build(params[:rule])

    respond_to do |format|
      if @rule.save
        format.html { redirect_to [@ruleset, @rule], notice: 'Rule was successfully created.' }
        format.json { render json: @rule, status: :created, location: @rule }
      else
        format.html { render action: "new" }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rules/1
  # PUT /rules/1.json
  def update
    @ruleset = Ruleset.find(params[:ruleset_id])
    @rule = @ruleset.rules.find(params[:id])

    respond_to do |format|
      if @rule.update_attributes(params[:rule])
        format.html { redirect_to [@ruleset, @rule], notice: 'Rule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @ruleset = Ruleset.find(params[:ruleset_id])
    @rule = @ruleset.rules.find(params[:id])
    @rule.destroy

    respond_to do |format|
      format.html { redirect_to ruleset_rules_url(@ruleset) }
      format.json { head :no_content }
    end
  end
end

spyads_dev/app/helpers/rules_helper.rb
module RulesHelper
end

spyads_dev/app/views/rules/_form.html.erb
<%= form_for([@ruleset, @rule]) do |f| %>
  <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_ownership %>
    <%= f.text_area :product_ownership, :class=>'longer' %>
  </div>
  <div class="field">
    <%= f.label :user_details %>
    <%= f.text_area :user_details, :class=>'longer' %>
  </div>
  <div class="field">
    <%= f.label :ad_id %>
    <%= select("rule", "ad_id",  Ad.all(:select=>"id,ad_title").collect { |a| [a.ad_title, a.id ] }, {:include_blank => false}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

spyads_dev/app/views/rules/edit.html.erb
<div id="full-pane">
  <h1>Edit rule</h1>

  <%= render 'form' %>

<%= link_to 'Show', [@ruleset, @rule] %> |
<%= link_to 'Back', ruleset_rules_path(@ruleset) %>
</div>

spyads_dev/app/views/rules/index.html.erb
<div id="full-pne">
  <h1>Listing Rules</h1>

  <table>
    <tr>
      <th>Product ownership</th>
      <th>User details</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @rules.each do |rule| %>
    <tr>
      <td><%= rule.product_ownership %></td>
      <td><%= rule.user_details %></td>
      <td><%= link_to 'Show', [@ruleset, rule] %></td>
      <td><%= link_to 'Edit', edit_ruleset_rule_path(@ruleset, rule) %></td>
      <td><%= link_to 'Destroy', [@ruleset, rule], confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>

  <br />

  <%= link_to 'Back to Ruleset', @ruleset %> |
  <%= link_to 'New Rule', new_ruleset_rule_path(@ruleset) %>
</div>

spyads_dev/app/views/rules/new.html.erb
<div id="full-pane">
  <h1>New rule</h1>

  <%= render 'form' %>

  <%= link_to 'Back', ruleset_rules_path(@ruleset) %>
</div>

spyads_dev/app/views/rules/show.html.erb
<div id="full-pane" class="show-pane">
<%= content_tag(:h1,"Rule")%>
<p id="notice"><%= notice %></p>
  <p>
    <b>Product Rules: </b>
    <%= @rule.product_ownership %>
  </p>
  <p>
    <b>User Rules: </b>
    <%= @rule.user_details %>
  </p>
  <p>
    <% unless @rule.ad_id.blank? %>
      <% ad = @rule.ad %>
      <b>Ad: </b>'<%=ad.product_name%>'  <%= link_to('View HTML', ad ) %> |  <%= link_to('View JSON', {:controller => "ads", :id => ad,:format => :json}) %>
    <% else %>
      <b>Ad not found</b>
    <% end %>
  </p>
</div>
<br>
<%= link_to 'Edit', edit_ruleset_rule_path(@ruleset, @rule) %> |
<%= link_to 'Back', ruleset_rules_path(@ruleset) %>