spyads_dev/config/routes.rb
Ixsellapp::Application.routes.draw do
  
  resources :rulesets do
    resources :rules do
    end
  end

  get "ixsell/query"

  get "ixsell/home"

  match "ixsell" => "ixsell#home"
  root :to => 'ixsell#home'

  resources :ads
  resources :users

end

spyads_dev/app/models/ruleset.rb
class Ruleset < ActiveRecord::Base
  has_many :rules
end

spyads_dev/app/controllers/rulesets_controller.rb
class RulesetsController < ApplicationController
  # GET /rulesets
  # GET /rulesets.json
  def index
    @rulesets = Ruleset.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rulesets }
    end
  end

  # GET /rulesets/1
  # GET /rulesets/1.json
  def show
    @ruleset = Ruleset.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ruleset }
    end
  end

  # GET /rulesets/new
  # GET /rulesets/new.json
  def new
    @ruleset = Ruleset.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ruleset }
    end
  end

  # GET /rulesets/1/edit
  def edit
    @ruleset = Ruleset.find(params[:id])
  end

  # POST /rulesets
  # POST /rulesets.json
  def create
    @ruleset = Ruleset.new(params[:ruleset])

    respond_to do |format|
      if @ruleset.save
        format.html { redirect_to @ruleset, notice: 'Ruleset was successfully created.' }
        format.json { render json: @ruleset, status: :created, location: @ruleset }
      else
        format.html { render action: "new" }
        format.json { render json: @ruleset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rulesets/1
  # PUT /rulesets/1.json
  def update
    @ruleset = Ruleset.find(params[:id])

    respond_to do |format|
      if @ruleset.update_attributes(params[:ruleset])
        format.html { redirect_to @ruleset, notice: 'Ruleset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ruleset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rulesets/1
  # DELETE /rulesets/1.json
  def destroy
    @ruleset = Ruleset.find(params[:id])
    @ruleset.destroy

    respond_to do |format|
      format.html { redirect_to rulesets_url }
      format.json { head :no_content }
    end
  end
end

spyads_dev/app/helpers/rulesets_helper.rb
module RulesetsHelper
end

spyads_dev/app/views/rulesets/_form.html.erb
<%= form_for(@ruleset) do |f| %>
  <% if @ruleset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ruleset.errors.count, "error") %> prohibited this ruleset from being saved:</h2>
      <ul>
      <% @ruleset.errors.full_messages.each do |msg| %>
        <%= content_tag(:li,  msg) %>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

spyads_dev/app/views/rulesets/_rules.html.erb
<br><br>
<b>Rules:</b><br>

<table>
  <tr>
    <th>Product ownership</th>
    <th>User details</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ruleset.rules.each do |rule| %>
  <tr>
    <td><%= rule.product_ownership %></td>
    <td><%= rule.user_details %></td>
    <td><%= link_to 'Show', [@ruleset, rule] %></td>
    <td><%= link_to 'Edit', edit_ruleset_rule_path(@ruleset, rule) %></td>
    <td><%= link_to 'Destroy', [@ruleset, rule], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<%= link_to 'New Rule', new_ruleset_rule_path(@ruleset) %><br><br>

spyads_dev/app/views/rulesets/edit.html.erb
<div id="full-pane">
  <h1>Edit Ruleset</h1>

  <%= render 'form' %>
  <%= render "rules" %>
  <%= link_to 'Show', @ruleset %> |
  <%= link_to 'Back', rulesets_path %>
</div>

spyads_dev/app/views/rulesets/index.html.erb
<div id="full-pane">
  <h1>List  Rulesets</h1>

  <table>
    <tr>
      <th align="left">ID</th>
      <th align="left">Name</th>
      <th align="left">Actions</th>
    </tr>

  <% @rulesets.each do |ruleset| %>
    <tr>
      <td><%= ruleset.id %></td>
      <td width="100px"><%= ruleset.name %></td>
      <td><%= link_to 'Show', ruleset %>&nbsp;
          <%= link_to 'Edit', edit_ruleset_path(ruleset) %>&nbsp;
          <%= link_to 'Destroy', ruleset, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>

  <br />

  <%= link_to 'New Ruleset', new_ruleset_path %>
</div>

spyads_dev/app/views/rulesets/new.html.erb
<div id="full-pane">
  <h1>New Ruleset</h1>
  <%= render 'form' %>
  <%= link_to 'Back', rulesets_path %>
</div>

spyads_dev/app/views/rulesets/show.html.erb
<div id="full-pane" class="show-pane">
  <p id="notice"><%= notice %></p>

  <b>Name:</b>
  <%= @ruleset.name %><br><br>
  <b>Rules:</b><br>
  <table>
    <tr>
      <th>Product ownership</th>
      <th>User details</th>
    </tr>

  <% @ruleset.rules.each do |rule| %>
    <tr>
      <td><%= rule.product_ownership %></td>
      <td><%= rule.user_details %></td>
    </tr>
  <% end %>
  </table>
</div>
<br><br>
<%= link_to 'Edit', edit_ruleset_path(@ruleset) %> |
<%= link_to 'Back', rulesets_path %>