spyads_dev/config/routes.rb
Ixsellapp::Application.routes.draw do
  
  resources :rulesets do
    resources :rules do
    end
  end

  get "ixsell/query"

  get "ixsell/home"

  match "ixsell" => "ixsell#home"
  root :to => 'ixsell#home'

  resources :ads
  resources :users

end

spyads_dev/app/models/ad.rb
class Ad < ActiveRecord::Base
  has_many :rules
end

spyads_dev/app/controllers/ads_controller.rb
class AdsController < ApplicationController
  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ads }
    end
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
    @ad = Ad.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ad }
    end
  end

  # GET /ads/new
  # GET /ads/new.json
  def new
    @ad = Ad.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ad }
    end
  end

  # GET /ads/1/edit
  def edit
    @ad = Ad.find(params[:id])
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(params[:ad])

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render json: @ad, status: :created, location: @ad }
      else
        format.html { render action: "new" }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ads/1
  # PUT /ads/1.json
  def update
    @ad = Ad.find(params[:id])

    respond_to do |format|
      if @ad.update_attributes(params[:ad])
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad = Ad.find(params[:id])
    @ad.destroy

    respond_to do |format|
      format.html { redirect_to ads_url }
      format.json { head :no_content }
    end
  end
end

spyads_dev/app/helpers/ads_helper.rb
module AdsHelper
  
  def display_ad ad, tracking=false
    
    cname = tracking && ad.ad_tracking.present? ? ad.ad_tracking.to_s : ""
 
    if ad.ad_body.present? 
      ad_content =  raw(ad.ad_body) 
    else
      ad_content =link_to( image_tag(ad.product_image), ad.product_link,{:class=>'int-box'})
    end
    # more  = content_tag(:div,'Were you looking for more information on',:class=>'looking-for')
    # title = content_tag(:div,ad.ad_title,:class=>'title')
    # text  = content_tag(:div,ad.ad_body,:class=>'body')
    # 
    # options_yes = {:id=>'learn-more' }
    # options_no  = {:id=>'no-thanks' }
    # options_img = {:class=>'int-box'}
    # 
    # if tracking  #clicks
    #   options_yes.merge!({:onclick =>"recordAnalyticsEvent('iad_yes_#{cname}','ad_learn_more_click');"})
    #   options_img.merge!({:onclick =>"recordAnalyticsEvent('iad_yes_#{cname}','ad_learn_more_click');"})
    #   options_no.merge!( {:onclick =>"recordAnalyticsEvent('iad_no_#{cname}','ad_no_thanks_click'); jQuery('#x-ad').hide();"})
    # end
    # 
    # yes = link_to('',ad.product_link ,options_yes)
    # no  = link_to('','#', options_no)
    # buttons = content_tag(:div,yes+no,:class=>'int-btn-set')
    # content = content_tag(:div,more + title + text + buttons, :class=>'int-content')
    # clear  = content_tag(:div,'',:class=>'clear')
    # 
    # middle = content_tag(:div, xlink + content + clear, :class=>'middle')

     
    if tracking  #impressions
      content_tag(:div, content_tag(:div, ad_content, :id=>"x-ad"), :id=>"ad_track",:class=>cname)
    else
      content_tag(:div,  ad_content , :id=>"x-ad")
    end
  end
end

spyads_dev/app/views/ads/_form.html.erb
<%= form_for(@ad) do |f| %>
  <% if @ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
      <% @ad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ad_title %>  
    <%= f.text_field :ad_title %>
  </div>
  <div class="field">
    <%= f.label :product_name %>  
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :ad_tracking %>  
    <%= f.text_field :ad_tracking %>
  </div>

  <p class="strong">Add an image OR your own HTML code:</p>
  <div class="group-fields">
    <h3>Image Ad</h3>
    <div class="field">
      <%= f.label :product_image %>
      <%= f.text_field :product_image, :class=>'longer' %>
    </div>
    <div class="field">
      <%= f.label :product_link  %>  
      <%= f.text_field :product_link, :class=>'longer' %>
    </div>
  </div>
  <p class="strong"> OR </p>
  <div class="group-fields">
    <h3>HTML Ad</h3>
    <div class="field">
      <%= f.label :ad_body %>  
      <%= f.text_area :ad_body, :class=>'longer' %>
    </div>
  </div>
  <div class="field">
    <%= f.label :is_active %>  
    <%= f.check_box :is_active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

spyads_dev/app/views/ads/edit.html.erb
<div id="full-pane">
  <h1>Edit Ad</h1>

  <%= render 'form' %>

  <%= link_to 'Show',  @ad  %> |
  <%= link_to 'Back', ads_path %>
</div>

spyads_dev/app/views/ads/index.html.erb
<div id="full-pane">
  <h1>List of Ads</h1>

  <table>
    <tr>
      <%= content_tag(:th, "ID") %>
      <%= content_tag(:th, "Product image") %>
      <%= content_tag(:th, "Product link") %>
      <%= content_tag(:th, "Product name") %>
      <%= content_tag(:th, "Tracking") %>
      <%= content_tag(:th, "Title") %>
      <%= content_tag(:th, "Body") %>
      <%#= content_tag(:th, "Active") %>
      <%= content_tag(:th, "") %>
      <%= content_tag(:th, "") %>
      <%= content_tag(:th, "") %>
    </tr>

  <% @ads.each do |ad| %>
    <tr>
      <%= content_tag(:td, ad.id ) %>
      <%= content_tag(:td, shorten_url(ad.product_image) ) %>
      <%= content_tag(:td, ad.product_link ) %>
      <%= content_tag(:td, ad.product_name ) %>
      <%= content_tag(:td, ad.ad_tracking ) %>
      <%= content_tag(:td, ad.ad_title ) %>
      <%= content_tag(:td, ad.ad_body ) %>
      <%#= content_tag(:td, ad.is_active ) %>
      <%= content_tag(:td, link_to( 'Show', ad) ) %>
      <%= content_tag(:td, link_to( 'Edit', edit_ad_path(ad)) ) %>
      <%= content_tag(:td, link_to( 'Destroy', ad, confirm: 'Are you sure?', method: :delete) ) %>
    </tr>
  <% end %>
  </table>

<br />

<%= link_to 'New Ad', new_ad_path %>

</div>

spyads_dev/app/views/ads/new.html.erb
<div id="full-pane">
  <h1>New Ad</h1>

  <%= render 'form' %>

  <%= link_to 'Back', ads_path %>
</div>

spyads_dev/app/views/ads/show.html.erb
<div id="full-pane" class="show-pane">
  <p id="notice"><%= notice %></p>

  <%= content_tag(:h2," Ad '#{@ad.ad_title}'" ) %>
  <%= content_tag(:div, display_ad(@ad,false), :class=>"gray_div") %>

</div>

<%= link_to 'Edit', edit_ad_path(@ad) %> |
<%= link_to 'Back', ads_path %>